# Generated by Django 4.2.4 on 2023-08-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_rename_user_pessoa_usuario_pessoa_profissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
