# Generated by Django 4.2.4 on 2023-09-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_remove_pessoa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='id_codificada',
            field=models.CharField(blank=True, editable=False, max_length=60, null=True, unique=True, verbose_name='ID Codificada'),
        ),
    ]
