# Generated by Django 4.2.4 on 2023-09-11 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_pessoa_id_codificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='conta_associada',
            field=models.OneToOneField(blank=True, help_text='Selecione a conta associada à pessoa se houver', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Conta associada à pessoa'),
        ),
    ]
