# Generated by Django 4.2.4 on 2023-09-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ('nome',), 'verbose_name': 'Plano plurianual', 'verbose_name_plural': 'Planos plurianuais'},
        ),
    ]
