# Generated by Django 4.2.4 on 2023-08-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao_prioritaria',
            options={'ordering': ('nome',), 'verbose_name': 'Ação prioritária', 'verbose_name_plural': 'Ações prioritárias'},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ('nome',), 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='programa_de_acoes_prioritarias',
            options={'ordering': ('nome',), 'verbose_name': 'Programa de ações prioritárias', 'verbose_name_plural': 'Programas de ações prioritárias'},
        ),
    ]
