# Generated by Django 4.2.4 on 2023-09-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('planos', '0002_alter_plano_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='pessoa_ancora_do_plano',
            field=models.ForeignKey(blank=True, help_text='Especifique a pessoa âncora, ou coordenadora deste plano, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa', verbose_name='Coordenador geral do Plano'),
        ),
    ]
