# Generated by Django 4.2.4 on 2023-09-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('locais', '0001_initial'),
        ('instituicoes', '0001_initial'),
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina um nome curto para o Programa.', max_length=150, null=True, verbose_name='Nome ou título do Programa')),
                ('objetivo_geral_do_programa', models.TextField(blank=True, help_text='Descreva de modo geral o que o Programa pretente alcançar na sociedade e no meio ambiente.', null=True, verbose_name='Objetivo geral do Programa')),
                ('resumo_descritivo_do_programa', models.TextField(blank=True, help_text='Descreva de modo geral o que é, quem está envolvido, onde se dará a execução, quando deverá ocorrer a execução, como e porque o Programa será executado.', null=True, verbose_name='Resumo descritivo do Programa')),
                ('fundos_de_execucao_do_programa', models.TextField(blank=True, help_text='Descreva brevemente as fontes de recursos para execução deste Programa.', null=True, verbose_name='Fundos de execução do Programa')),
                ('prazo_de_execucao_do_programa', models.CharField(blank=True, choices=[('ML', 'MUITO LONGO (mais de 8 anos)'), ('L', 'LONGO (de 4 a 8 anos)'), ('M', 'MÉDIO (de dois a 4 anos)'), ('C', 'CURTO (de 1 a dois anos)'), ('MC', 'MUITO CURTO (menos de 1 ano)')], help_text='Selecione o prazo estabelecido para execução completa deste Programa', max_length=2, null=True)),
                ('escopo_geografico_do_programa', models.CharField(blank=True, choices=[('NAC', 'Nacional'), ('MRE', 'Macroregional'), ('EST', 'Estadual'), ('MIC', 'Microregional'), ('MUN', 'Municipal'), ('LOC', 'Local')], help_text='Selecione o escopo geográfico do Programa', max_length=3, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='programas')),
                ('instituicao_ancora_do_programa', models.ForeignKey(blank=True, help_text='Selecione a Instituição considerada a proponente principal ou a âncora do Programa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.instituicao', verbose_name='Instituição âncora do Programa')),
                ('municipio_ancora_do_programa', models.ForeignKey(blank=True, help_text='Selecione o município cosiderado a sede ou âncora deste programa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.municipio', verbose_name='Município âncora do Programa')),
                ('pessoa_ancora_do_programa', models.ForeignKey(blank=True, help_text='Especifique a pessoa âncora, ou coordenadora deste programa, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa', verbose_name='Coordenador geral')),
                ('plano_vinculado_ao_programa', models.ForeignKey(blank=True, help_text='Selecione o Plano a que este Programa se vincula.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_vinculados_ao_plano', to='planos.plano', verbose_name='Plano vinculado a este Programa')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Diretriz_especifica_de_programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina um título ou nome curto para a diretriz específica do Programa.', max_length=120, null=True, verbose_name='Nome ou título da diretriz específica')),
                ('descricao_da_diretriz_especifica', models.TextField(blank=True, help_text='Descreva a diretriz específica de forma genérica objetivando nortear os projetos que se vincularão a ela.', max_length=600, null=True, verbose_name='Descrição da diretriz específica do programa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('programa_vinculado_a_diretriz_especifica', models.ForeignKey(blank=True, help_text='Selecione o Programa ao qual a diretriz específica está vinculado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programas.programa', verbose_name='Programa vinculado')),
            ],
            options={
                'verbose_name': 'Diretriz específica',
                'verbose_name_plural': 'Diretrizes específicas',
                'ordering': ('nome',),
            },
        ),
    ]
