# Generated by Django 4.2.4 on 2023-09-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0002_alter_plano_options'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ('nome',), 'verbose_name': 'Programa de mobilização de projetos', 'verbose_name_plural': 'Programas de mobilização de projetos'},
        ),
        migrations.AlterField(
            model_name='diretriz_especifica_de_programa',
            name='programa_vinculado_a_diretriz_especifica',
            field=models.ForeignKey(blank=True, help_text='Selecione o Programa de mobilização de projetos ao qual a diretriz específica está vinculado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programas.programa', verbose_name='Programa de mobilização de projetos vinculado'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nome',
            field=models.CharField(blank=True, help_text='Defina um nome curto para o Programa de mobilização de projetos.', max_length=150, null=True, verbose_name='Nome ou título do Programa'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='objetivo_geral_do_programa',
            field=models.TextField(blank=True, help_text='Descreva de modo geral o que este Programa pretente alcançar na sociedade e no meio ambiente.', null=True, verbose_name='Objetivo geral do Programa de mobilização de projetos'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='plano_vinculado_ao_programa',
            field=models.ForeignKey(blank=True, help_text='Selecione o Plano a que este Programa se vincula.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_vinculados_ao_plano', to='planos.plano', verbose_name='Plano Plurianual vinculado a este Programa de mobilização de projetos'),
        ),
    ]
