# Generated by Django 4.2.4 on 2023-09-02 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_alter_plano_pessoa_ancora_do_plano'),
        ('programas', '0002_alter_programa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='plano_vinculado_ao_programa',
            field=models.ForeignKey(blank=True, help_text='Selecione o Plano a que este Programa se vincula.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_vinculados_ao_plano', to='planos.plano', verbose_name='Plano Plurianual vinculado'),
        ),
    ]
