# Generated by Django 4.2.4 on 2023-09-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microbacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Insira o nome da microbacia hidrográfica.', max_length=80, null=True, unique=True, verbose_name='Nome da microbacia hidrográfica')),
            ],
            options={
                'verbose_name': 'Microbracia',
                'verbose_name_plural': 'Microbacias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Insira o nome do município.', max_length=80, null=True, unique=True, verbose_name='Nome do município')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Unidade_de_referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', help_text='Insira um nome ou título para a unidade de referência', max_length=120, null=True, unique=True, verbose_name='Nome da unidade de referência')),
                ('latitude_da_ur', models.CharField(blank=True, default='-00.000000', help_text='Insira a latitude da UR, em graus decimais com sinais. Exemplo: -28.123456', max_length=15, verbose_name='Latitude')),
                ('longitude_da_ur', models.CharField(blank=True, default='-00.000000', help_text='Insira a longitude em graus decimais com sinais. Exemplo: -50.123456', max_length=15, verbose_name='Longitude')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='locais/unidades_de_referencia')),
                ('municipio_da_ur', models.ForeignKey(blank=True, help_text='Selecione o municipio onde se localiza a UR.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.municipio', verbose_name='Município da UR')),
            ],
            options={
                'verbose_name': 'Unidade de referência',
                'verbose_name_plural': 'Unidades de referência',
                'ordering': ('nome',),
            },
        ),
    ]
