# Generated by Django 4.2.4 on 2023-08-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_rename_user_pessoa_usuario_pessoa_profissao'),
        ('instituicoes', '0001_initial'),
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microbacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Insira o nome da microbacia hidrográfica.', max_length=80, null=True, unique=True, verbose_name='Nome da microbacia hidrográfica')),
            ],
            options={
                'verbose_name': 'Microbracia',
                'verbose_name_plural': 'Microbacias',
                'ordering': ('nome',),
            },
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nome',
            field=models.CharField(blank=True, help_text='Insira o nome do município.', max_length=80, null=True, unique=True, verbose_name='Nome do município'),
        ),
        migrations.CreateModel(
            name='Unidade_de_referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', help_text='Insira um nome ou título para a unidade de referência', max_length=120, null=True, unique=True, verbose_name='Nome da unidade de referência')),
                ('latitude_da_ur', models.CharField(blank=True, default='-00.000000', help_text='Insira a latitude da UR, em graus decimais com sinais. Exemplo: -28.123456', max_length=15, verbose_name='Latitude')),
                ('longitude_da_ur', models.CharField(blank=True, default='-00.000000', help_text='Insira a longitude em graus decimais com sinais. Exemplo: -50.123456', max_length=15, verbose_name='Longitude')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='locais/unidades_de_referencia')),
                ('municipio_da_ur', models.ForeignKey(blank=True, help_text='Selecione o municipio onde se localiza a UR.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.municipio', verbose_name='Município da UR')),
                ('proprietario_pf_de_ur', models.ForeignKey(blank=True, help_text='Selecione o nome do proprietário do local se for Pessoa Física.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa', verbose_name='Pessoa física proprietária do local')),
                ('proprietario_pj_da_ur', models.ForeignKey(blank=True, help_text='Selecione uma instituição proprietária da UR, se for Pessoa Jurídica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.instituicao', verbose_name='Pessoa jurídica proprietária do local')),
            ],
            options={
                'verbose_name': 'Unidade de de referência',
                'verbose_name_plural': 'Unidades de referência',
                'ordering': ('nome',),
            },
        ),
    ]
