# Generated by Django 4.2.4 on 2023-08-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_microbacia_alter_municipio_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidade_de_referencia',
            old_name='proprietario_pj_da_ur',
            new_name='proprietario_pj_de_ur',
        ),
    ]
