# Generated by Django 4.2.4 on 2023-09-03 11:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade_de_referencia',
            name='latitude_da_ur',
        ),
        migrations.RemoveField(
            model_name='unidade_de_referencia',
            name='longitude_da_ur',
        ),
        migrations.AddField(
            model_name='unidade_de_referencia',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Encontre o local da sede da UR no mapa e depois insira um marcador sobre ela.', null=True, srid=4326, verbose_name='Local da atividade'),
        ),
    ]
