# Generated by Django 4.2.4 on 2023-08-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0003_rename_proprietario_pj_da_ur_unidade_de_referencia_proprietario_pj_de_ur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade_de_referencia',
            options={'ordering': ('nome',), 'verbose_name': 'Unidade de referência', 'verbose_name_plural': 'Unidades de referência'},
        ),
    ]
