# Generated by Django 4.2.4 on 2023-08-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('pessoas', '0002_rename_user_pessoa_usuario_pessoa_profissao'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivo_especifico_de_projeto',
            old_name='descrição_do_objetivo_especifico',
            new_name='descricao_do_objetivo_especifico',
        ),
        migrations.AddField(
            model_name='atividade',
            name='categoria_de_atividade',
            field=models.ForeignKey(blank=True, help_text='Selecione a categoria mais adequada para esta atividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria_de_atividade', verbose_name='Categoria de atividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='coordenador',
            field=models.ForeignKey(blank=True, help_text='Especifique a pessoa âncora ou coordenadora desta atividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa', verbose_name='Coordenador(a) de Atividade'),
        ),
    ]
