# Generated by Django 4.2.4 on 2023-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='fundos_estimados_de_contra_partida',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Especifique o total de contra-partida que este projeto vai acessar ou acessou.', max_digits=10, null=True, verbose_name='Total de fundos de contra-partida'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='fundos_estimados_do_verde_sinos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Especifique o total de fundos do VerdeSinos que este Projeto vai acessar ou acessou.', max_digits=10, null=True, verbose_name='Total de fundos do VerdeSinos'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='urs_vinculadas_ao_projeto',
            field=models.ManyToManyField(blank=True, help_text='Selecione uma ou mais URs que estão diretamente relacionadas ao projeto.', related_name='projetos_vinculados_a_ur', to='locais.unidade_de_referencia', verbose_name='UR(s) vinculada(s) ao Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor_total_do_projeto',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor total do Projeto'),
        ),
    ]
