# Generated by Django 4.2.4 on 2023-08-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_descrição_do_objetivo_especifico_objetivo_especifico_de_projeto_descricao_do_objetivo_especif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ('nome',), 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
    ]
