# Generated by Django 4.2.4 on 2023-09-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_fundos_estimados_de_contra_partida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='fundos_estimados_de_contra_partida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Especifique o total de contra-partida que este projeto vai acessar ou acessou.', max_digits=10, verbose_name='Total de fundos de contra-partida'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='fundos_estimados_do_verde_sinos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Especifique o total de fundos do VerdeSinos que este Projeto vai acessar ou acessou.', max_digits=10, verbose_name='Total de fundos do VerdeSinos'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor_total_do_projeto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor total do Projeto'),
        ),
    ]
