# Generated by Django 4.2.4 on 2023-08-29 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_atividade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo_especifico_de_projeto',
            name='percentual_de_alcance_atingido',
            field=models.IntegerField(blank=True, default=0, help_text='Insira um valor de 0 a 100 correspondente ao percentual de alcance deste objetivo até o momento.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual de alcance atingido'),
        ),
    ]
