# Generated by Django 4.2.4 on 2023-09-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_categoria_de_plano_options'),
        ('projetos', '0003_alter_projeto_fundos_estimados_de_contra_partida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo_especifico_de_projeto',
            name='categoria_de_objetivo_especifico',
            field=models.ForeignKey(blank=True, help_text='Selecione a categoria mais adequada para este objetivo específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria_de_objetivo_especifico', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='objetivo_especifico_de_projeto',
            name='projeto_vinculado_ao_objetivo_especifico',
            field=models.ForeignKey(blank=True, help_text='Selecione o Projeto a que este objetivo específico, sub-projeto ou meta se vincula.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.projeto', verbose_name='Projeto vinculado'),
        ),
    ]
