# Generated by Django 4.2.4 on 2023-09-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_objetivo_especifico_de_projeto_categoria_de_objetivo_especifico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('01', 'Crianças e adolescentes'), ('02', 'Adultos da comunidade'), ('03', 'Profissionais da educação'), ('04', 'Profissionais da comunicação'), ('05', 'Autoridades públicas'), ('06', 'Outro público')], help_text='Selecione o tipo de público envolvido.', max_length=2, null=True, verbose_name='Categoria de público')),
                ('descricao', models.CharField(blank=True, help_text='Inclua uma breve descrição do público envolvido.', max_length=80, null=True, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(default=0, help_text='Insira a quantidade de pessoas envolvidas da categoria selecionada.', verbose_name='QTD')),
                ('atividade', models.ForeignKey(blank=True, help_text='Selecione a atividade vinculada ao público envolvido.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publico', to='projetos.atividade', verbose_name='Atividade vinculada.')),
            ],
            options={
                'verbose_name': 'Público',
                'verbose_name_plural': 'Públicos',
                'ordering': ('id',),
            },
        ),
    ]
