# Generated by Django 4.2.4 on 2023-08-30 10:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_objetivo_especifico_de_projeto_percentual_de_alcance_atingido'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Especifique o local da atividade selecionando o ponto geográfico no mapa.', null=True, srid=4326, verbose_name='Local da atividade'),
        ),
    ]
