# Generated by Django 4.2.4 on 2023-08-30 14:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_atividade_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='resultados',
            field=models.TextField(blank=True, help_text='Registre aqui o que se alcançou com a atividade depois de concluída.', max_length=600, null=True, verbose_name='Resultados'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Encontre o local da atividade no mapa e depois insira um marcador sobre ele.', null=True, srid=4326, verbose_name='Local da atividade'),
        ),
    ]
