# Generated by Django 4.2.4 on 2023-09-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_categoria_de_publico_descricao'),
        ('projetos', '0006_remove_publico_tipo_atividade_publico_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='publico_total',
        ),
        migrations.RemoveField(
            model_name='publico',
            name='descricao',
        ),
        migrations.AddField(
            model_name='publico',
            name='detalhamento',
            field=models.CharField(blank=True, help_text='Inclua uma breve descrição do público envolvido.', max_length=250, null=True, verbose_name='Detalhamento'),
        ),
        migrations.AlterField(
            model_name='publico',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Selecione o tipo de público envolvido.', null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria_de_publico', verbose_name='Categoria de público'),
        ),
    ]
