# Generated by Django 4.2.4 on 2023-09-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_categoria_de_publico_descricao'),
        ('projetos', '0007_remove_atividade_publico_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='sub_categoria_de_atividade',
            field=models.ForeignKey(blank=True, help_text='Selecione a subcategoria da atividade.', null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.sub_categoria_de_atividade', verbose_name='Subcategoria'),
        ),
    ]
