# Generated by Django 4.2.4 on 2023-09-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_categoria_de_publico_descricao'),
        ('projetos', '0008_atividade_sub_categoria_de_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='publico_envolvido',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='categoria_de_atividade',
            field=models.ForeignKey(blank=True, help_text='Selecione a categoria mais adequada para esta atividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria_de_atividade', verbose_name='Categoria'),
        ),
    ]
