# Generated by Django 4.2.4 on 2023-09-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_atividade_publico_envolvido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publico',
            options={'ordering': ('id',), 'verbose_name': 'Público envolvido', 'verbose_name_plural': 'Públicos envolvidos'},
        ),
        migrations.AlterField(
            model_name='atividade',
            name='publico_envolvido',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Público diretamente envolvido'),
        ),
    ]
