# Generated by Django 4.2.4 on 2023-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_alter_publico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='publico_envolvido',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Público diretamente envolvido'),
        ),
    ]
