# Generated by Django 4.2.4 on 2023-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_alter_atividade_publico_envolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo_especifico_de_projeto',
            name='parent_subprojects',
            field=models.ManyToManyField(blank=True, related_name='child_subprojects', to='projetos.objetivo_especifico_de_projeto', verbose_name='Subprojeto vinculado'),
        ),
    ]
