# Generated by Django 4.2.4 on 2023-09-11 11:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_remove_pessoa_usuario'),
        ('fundos', '0017_remove_requisicao_objetivo_especifico_vinculado'),
        ('categorias', '0013_categoria_de_subprojeto_subcategoria_de_atividade_and_more'),
        ('projetos', '0012_objetivo_especifico_de_projeto_parent_subprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subprojeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina um nome ou título curto para este subprojeto.', max_length=120, null=True, verbose_name='Nome ou título do subprojeto')),
                ('descricao_do_subprojeto', models.TextField(blank=True, help_text='Descreva o que este subprojeto pretende alcançar.', max_length=300, null=True, verbose_name='Descrição do subprojeto')),
                ('indicadores', models.TextField(blank=True, help_text='Especifique aqui o(s) indicador(es) que evidenciarão o alcance deste subprojeto.', max_length=300, null=True, verbose_name='Indicadores')),
                ('verificacao', models.TextField(blank=True, help_text='Especifique aqui como serão verificados os indicadores de conclusão deste subprojeto, isto é que instrumentos, metodologia, processos.', max_length=300, null=True, verbose_name='Métodos de verificação')),
                ('percentual_de_conclusao', models.IntegerField(blank=True, default=0, help_text='Insira um valor de 0 a 100 correspondente ao percentual de conclusão deste subprojeto até o momento.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual de alcance atingido')),
                ('inicio', models.DateField(blank=True, default=datetime.date.today, help_text='Especifique uma data de início para o Subprojeto.', verbose_name='Data de início do Subprojeto')),
                ('fim', models.DateField(blank=True, default=datetime.date.today, help_text='Defina uma data para a conclusão do Subprojeto.', verbose_name='Data de fim do Subprojeto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='projetos/subprojetos')),
                ('categoria_de_subprojeto', models.ForeignKey(blank=True, help_text='Selecione a categoria mais adequada para este subprojeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria_de_subprojeto', verbose_name='Categoria')),
                ('coordenador', models.ForeignKey(blank=True, help_text='Especifique a pessoa âncora ou coordenadora deste subprojeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa', verbose_name='Coordenador(a) de Subprojeto')),
                ('projeto_vinculado_ao_subprojeto', models.ForeignKey(blank=True, help_text='Selecione o Projeto a que este Subprojeto se vincula.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.projeto', verbose_name='Projeto vinculado')),
                ('subprojetos_relacionados', models.ManyToManyField(blank=True, related_name='subprojetos_relacionados_a_subprojetos', to='projetos.subprojeto', verbose_name='Subprojeto relacionado')),
            ],
            options={
                'verbose_name': 'Subprojeto',
                'verbose_name_plural': 'Subprojetos',
                'ordering': ('nome',),
            },
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='etapa_vinculada',
            new_name='etapa_vinculada_a_atividade',
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='projeto_vinculado',
            new_name='projeto_vinculado_a_atividade',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='objetivo_especifico_vinculado',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='sub_categoria_de_atividade',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='objetivo_especifico_vinculado_a_etapa',
        ),
        migrations.AddField(
            model_name='atividade',
            name='subcategoria_de_atividade',
            field=models.ForeignKey(blank=True, help_text='Selecione a subcategoria da atividade.', null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.subcategoria_de_atividade', verbose_name='Subcategoria'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='nome',
            field=models.CharField(blank=True, help_text='Defina um nome ou título para a etapa de um Subprojeto.', max_length=120, null=True, verbose_name='Nome ou título da etapa'),
        ),
        migrations.DeleteModel(
            name='Objetivo_especifico_de_projeto',
        ),
        migrations.AddField(
            model_name='atividade',
            name='subprojeto_vinculado_a_atividade',
            field=models.ForeignKey(blank=True, help_text='Selecione o objetivo específico a que esta atividade se vincula, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.subprojeto', verbose_name='Objetivo específico vinculado'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='subprojeto_vinculado_a_etapa',
            field=models.ForeignKey(blank=True, help_text='Selecione o Subprojeto a que esta etapa se vincula.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.subprojeto', verbose_name='Subprojeto vinculado à etapa'),
        ),
    ]
