# Generated by Django 4.2.4 on 2023-09-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_de_atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma categoria à atividade ainda não existente no sistema.', max_length=60, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descreva esta categoria no âmbito das atividades.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de atividade',
                'verbose_name_plural': 'Categorias de atividade',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Categoria_de_objetivo_especifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma categoria ao Objetivo Especifico ainda não existente no sistema.', max_length=60, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descreva esta categoria no âmbito dos objetivos específicos de um projeto.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de objetivo, sub-projeto ou meta',
                'verbose_name_plural': 'Categorias de objetivos, sub-projetos ou metas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Categoria_de_plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma categoria de plano ainda não existent no sistema.', max_length=150, null=True, unique=True, verbose_name='Categoria de Plano')),
                ('descricao', models.TextField(blank=True, help_text='Descreva suscintamente que grupo de planos esta categoria inclui.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de plano',
                'verbose_name_plural': 'Categorias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina um nome ou título curto para o fundo de financiamento', max_length=120, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Propósito do fundo.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fundo de financiamento',
                'verbose_name_plural': 'Fundos de financiamento',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma profissão ainda não existente no sistema', max_length=60, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descreva essa profissão no âmbito do que fazem os seus profissionais', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': 'Profissões',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Sub_categoria_de_atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma sub-categoria da categoria de atividade.', max_length=60, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descreva essa sub-categoria de atividade.no âmbito das categorias de atividades.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sub-categoria de atividade',
                'verbose_name_plural': 'Sub-categorias de atividade',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Sub_categoria_de_objetivo_especifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma sub-categoria da categoria de objetivo específico, sub-projeto ou meta.', max_length=60, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descreva essa sub-categoria no âmbito dos objetivos específicos de um projeto.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sub-categoria de objetivo específico',
                'verbose_name_plural': 'Sub-categorias de objetivos específicos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Unidade_de_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma profissão ainda não existente no sistema', max_length=30, null=True, unique=True)),
                ('abreviatura', models.CharField(blank=True, help_text='Abreviação da unidade de medida.', max_length=5, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da unidade de medida.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidade de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ('nome',),
            },
        ),
    ]
