# Generated by Django 4.2.4 on 2023-09-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='mantenedora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.instituicao', verbose_name='Instituição mantenedora'),
        ),
        migrations.AddField(
            model_name='categoria_de_objetivo_especifico',
            name='sub_categorias',
            field=models.ManyToManyField(related_name='Categorias_de_objetivos_especificos', to='categorias.sub_categoria_de_objetivo_especifico'),
        ),
        migrations.AddField(
            model_name='categoria_de_atividade',
            name='sub_categorias',
            field=models.ManyToManyField(related_name='Categorias_de_atividades', to='categorias.sub_categoria_de_atividade'),
        ),
    ]
