# Generated by Django 4.2.4 on 2023-09-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_de_plano',
            options={'ordering': ('nome',), 'verbose_name': 'Categoria de plano', 'verbose_name_plural': 'Categorias de planos'},
        ),
    ]
