# Generated by Django 4.2.4 on 2023-08-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
        ('categorias', '0002_unidade_de_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina um nome ou título curto para o fundo de financiamento', max_length=120, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Propósito do fundo.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('mantenedora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.instituicao', verbose_name='Instituição mantenedora')),
            ],
            options={
                'verbose_name': 'Fundo de financiamento',
                'verbose_name_plural': 'Fundos de financiamento',
                'ordering': ('nome',),
            },
        ),
    ]
