# Generated by Django 4.2.4 on 2023-09-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_categoria_de_plano_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_de_publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma categoria de público atendido ou envolvido em atividades de projetos.', max_length=100, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de público',
                'verbose_name_plural': 'Categorias de público',
                'ordering': ('nome',),
            },
        ),
    ]
