# Generated by Django 4.2.4 on 2023-09-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_categoria_de_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_de_publico',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descreva que tipo de público esta categoria inclui.', max_length=300, null=True),
        ),
    ]
