# Generated by Django 4.2.4 on 2023-09-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_categoria_de_publico_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='inserido_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
