# Generated by Django 4.2.4 on 2023-09-05 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0009_categoria_de_plano_atualizado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_de_objetivo_especifico',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_de_objetivos_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria_de_objetivo_especifico',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_de_objetivos_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria_de_objetivo_especifico',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria_de_objetivo_especifico',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_categoria_de_objetivo_especifico',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias_de_objetivos_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sub_categoria_de_objetivo_especifico',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias_de_objetivos_criadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
