# Generated by Django 4.2.4 on 2023-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0010_categoria_de_objetivo_especifico_atualizado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissao',
            name='id_codificada',
            field=models.CharField(blank=True, editable=False, max_length=60, null=True, unique=True, verbose_name='ID Codificada'),
        ),
    ]
