# Generated by Django 4.2.4 on 2023-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0011_profissao_id_codificada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_de_despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma categoria de itens de despesa.', max_length=50, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição de categoria de itens de despesa.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de despesa',
                'verbose_name_plural': 'Categorias de despesa',
                'ordering': ('nome',),
            },
        ),
    ]
