# Generated by Django 4.2.4 on 2023-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0012_categoria_de_despesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_de_subprojeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma categoria ao Subprojeto.', max_length=60, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descreva esta categoria no âmbito dos subprojetos de um projeto.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Subprojeto, objetivo específico ou meta',
                'verbose_name_plural': 'Categorias de Subprojetos, objetivos específicos ou metas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Subcategoria_de_atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma subcategoria da categoria de atividade.', max_length=60, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descreva essa subcategoria de atividade.no âmbito das categorias de atividades.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subcategoria de atividade',
                'verbose_name_plural': 'Subcategorias de atividade',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Subcategoria_de_subprojeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Defina uma subcategoria da categoria de Subprojeto, objetivo específico ou meta.', max_length=60, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descreva essa subcategoria no âmbito dos subprojetos de um projeto.', max_length=300, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Subcategoria de Subprojeto',
                'verbose_name_plural': 'Subcategorias de Subprojetos',
                'ordering': ('nome',),
            },
        ),
        migrations.RemoveField(
            model_name='categoria_de_objetivo_especifico',
            name='atualizado_por',
        ),
        migrations.RemoveField(
            model_name='categoria_de_objetivo_especifico',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='categoria_de_objetivo_especifico',
            name='sub_categorias',
        ),
        migrations.RemoveField(
            model_name='sub_categoria_de_objetivo_especifico',
            name='atualizado_por',
        ),
        migrations.RemoveField(
            model_name='sub_categoria_de_objetivo_especifico',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='categoria_de_atividade',
            name='sub_categorias',
        ),
    ]
