# Generated by Django 4.2.4 on 2023-09-11 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0013_categoria_de_subprojeto_subcategoria_de_atividade_and_more'),
        ('projetos', '0013_subprojeto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria_de_objetivo_especifico',
        ),
        migrations.DeleteModel(
            name='Sub_categoria_de_atividade',
        ),
        migrations.DeleteModel(
            name='Sub_categoria_de_objetivo_especifico',
        ),
        migrations.AddField(
            model_name='subcategoria_de_subprojeto',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias_de_subprojetos_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoria_de_subprojeto',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias_de_subprojetos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria_de_subprojeto',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_de_subprojetos_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria_de_subprojeto',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_de_subprojetos_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria_de_subprojeto',
            name='subcategorias',
            field=models.ManyToManyField(related_name='Categorias_de_subprojetos', to='categorias.subcategoria_de_subprojeto'),
        ),
        migrations.AddField(
            model_name='categoria_de_atividade',
            name='subcategorias',
            field=models.ManyToManyField(related_name='Categorias_de_atividades', to='categorias.subcategoria_de_atividade'),
        ),
    ]
