# Generated by Django 4.2.4 on 2023-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0014_delete_categoria_de_objetivo_especifico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_de_subprojeto',
            options={'ordering': ('nome',), 'verbose_name': 'Categoria de subprojeto, objetivo específico ou meta', 'verbose_name_plural': 'Categorias de subprojetos, objetivos específicos ou metas'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria_de_subprojeto',
            options={'ordering': ('nome',), 'verbose_name': 'Subcategoria de subprojeto, objetivo específico ou meta', 'verbose_name_plural': 'Subcategorias de subprojetos, objetivos específicos ou metas'},
        ),
        migrations.AlterField(
            model_name='categoria_de_subprojeto',
            name='nome',
            field=models.CharField(blank=True, help_text='Defina uma categoria ao subprojeto.', max_length=60, null=True, unique=True),
        ),
    ]
