# Generated by Django 4.2.4 on 2023-09-11 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0016_categoria_de_despesa_atualizado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade_de_medida',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_de_medida_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidade_de_medida',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_de_medida_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundos_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundos_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
