# Generated by Django 4.2.4 on 2023-09-11 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0017_unidade_de_medida_atualizado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria_de_atividade',
            name='subcategorias',
        ),
        migrations.RemoveField(
            model_name='categoria_de_subprojeto',
            name='subcategorias',
        ),
        migrations.RemoveField(
            model_name='profissao',
            name='id_codificada',
        ),
        migrations.AddField(
            model_name='categoria_de_atividade',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_de_atividades_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria_de_atividade',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_de_atividade_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria_de_publico',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_de_publico_alvo_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria_de_publico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_de_publico_alvo_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoria_de_atividade',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias_de_atividades_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoria_de_atividade',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Selecione a categoria de atividade a que esta subcategoria pertence.', null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria_de_atividade', verbose_name='Categoria de atividade'),
        ),
        migrations.AddField(
            model_name='subcategoria_de_atividade',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias_de_atividade_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoria_de_subprojeto',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Selecione a categoria de subprojeto, objetivo específico ou meta a que esta subcategoria pertence.', null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria_de_subprojeto', verbose_name='Categoria de subprojeto, objetivo específico ou meta'),
        ),
    ]
