# Generated by Django 4.2.4 on 2023-09-02 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Insira o nome ou título do serviço, material ou maquinário (item de despesa no orçamento)', max_length=120, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('MO', 'Mão de obra ou serviço'), ('MT', 'Materiais ou insumos'), ('MQ', 'Máquinas ou equipamentos')], help_text='Selecione o tipo mais adequado de despesa.', max_length=2, null=True, verbose_name='Tipo de despesa')),
                ('descricao', models.TextField(blank=True, help_text='Inclua uma breve descrição do item de despesa no orçamento quando houver especificações técnicas.', null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Item de despesa',
                'verbose_name_plural': 'Itens de despesa',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, help_text='Seleciona a data do orçamento fornecido.', null=True)),
                ('numero_NF', models.CharField(blank=True, help_text='Insira o número da NF após compra confirmada', max_length=30, null=True)),
                ('data_NF', models.DateField(blank=True, help_text='Insira da data de emissão da NF.', null=True, verbose_name='Data da NF')),
                ('numero_RPA', models.CharField(blank=True, help_text='Insira o número do RPS após a compra confirmada', max_length=30, null=True)),
                ('data_RPA', models.DateField(blank=True, help_text='Insira da data de emissão do RPA.', null=True, verbose_name='Data da NF')),
                ('validade', models.PositiveIntegerField(blank=True, default=30, help_text='Especifique por quantos dias este orçamento é válido.', null=True, verbose_name='Validade do orçamento')),
                ('forma_de_garantia', models.CharField(blank=True, help_text='Explicite a forma e tempo de garantia do fornecedor.', max_length=200, null=True, verbose_name='Forma e tempo de garantia do fornecedor')),
                ('exclui', models.TextField(blank=True, help_text='Especifique o que não está incluso neste orçamento, caso seja relevante esclarecer.', null=True, verbose_name='O que não está incluso neste orçamento')),
                ('dados_para_pagamento', models.TextField(blank=True, help_text='Inclua os dados para pagamento deste orçamento conforme preferência do fornecedor (Pix, dados para depósito, etc.).', null=True, verbose_name='Dados para pagamento')),
                ('observacoes', models.TextField(blank=True, help_text='Insira quaisquer observações adicionais que considerar pertinente sobre esse orçamento.', null=True, verbose_name='Observações adicionais')),
                ('total_do_orcamento', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor total do orçamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='fundos/orcamentos')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Especifique a quantidade que deseja adquirir considerando a unidade de medida do item de despesa.', max_digits=6, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Especifique o preço unitário do item de orçamento.', max_digits=10, verbose_name='Preço unitário')),
                ('subtotal_do_pedido', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal do item de despesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data da solicitação')),
                ('cronograma', models.TextField(blank=True, help_text='Especifique um cronograma ou período estimado de relaização das atividades com os fundos solicitados.', max_length=300, null=True, verbose_name='Cronograma de execução')),
                ('urgencia', models.CharField(choices=[('Alta', 'ALTA'), ('Média', 'MÉDIA'), ('Baixa', 'BAIXA')], help_text='Selecione o caráter de urgência para liberação de fundos.', max_length=5, verbose_name='Caráter de urgência')),
                ('observacoes', models.TextField(blank=True, help_text='Inclua quaiquer observações que considerar necessário.', null=True, verbose_name='Observações')),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='fundos/requisicoes')),
            ],
            options={
                'verbose_name': 'Requisiçáo de fundos',
                'verbose_name_plural': 'Requisições de fundos',
                'ordering': ('id',),
            },
        ),
    ]
