# Generated by Django 4.2.4 on 2023-08-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_rename_user_pessoa_usuario_pessoa_profissao'),
        ('fundos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_de_fundos',
            name='responsavel_pelo_preenchimento',
            field=models.ForeignKey(blank=True, help_text='Selecione a pessoa responsável pelo preenchimento desta solicitação.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa', verbose_name='Responsável pelo preenchimento'),
        ),
    ]
