# Generated by Django 4.2.4 on 2023-08-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_unidade_de_medida'),
        ('fundos', '0002_alter_solicitacao_de_fundos_responsavel_pelo_preenchimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_de_orcamento',
            name='unidade_de_medida',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade de medida do ítem de orçamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.unidade_de_medida'),
        ),
    ]
