# Generated by Django 4.2.4 on 2023-09-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='orcamento',
            field=models.ForeignKey(blank=True, help_text='Selecione o orçamento a que este pedido de itens de despesa faz parte.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundos.orcamento', verbose_name='Orçamento a que este pedido pertence'),
        ),
    ]
