# Generated by Django 4.2.4 on 2023-08-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0003_alter_item_de_orcamento_unidade_de_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_de_orcamento',
            name='orcamento',
            field=models.ForeignKey(blank=True, help_text='Selecione o orçamento no qual este item pertence.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_orcados', to='fundos.orcamento_para_solicitacao_de_fundos'),
        ),
    ]
