# Generated by Django 4.2.4 on 2023-09-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0004_compra_delete_pedido_alter_orcamento_itens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ('id',), 'verbose_name': 'Lista de compra', 'verbose_name_plural': 'Listas de compras'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',), 'verbose_name': 'Produto ou serviço', 'verbose_name_plural': 'Produtos ou serviços'},
        ),
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ('id',), 'verbose_name': 'Orçamento de fornecedor(a)', 'verbose_name_plural': 'Orçamentos de fornecedores(as)'},
        ),
        migrations.AlterField(
            model_name='compra',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Selecione o item de despesa para esta compra.', null=True, on_delete=django.db.models.deletion.CASCADE, to='fundos.item', verbose_name='Produto ou serviço'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(blank=True, choices=[('MO', 'Mão de obra ou serviços'), ('MT', 'Ferramentas manuais, materiais ou insumos'), ('MQ', 'Máquinas ou equipamentos eletroeletrônicos')], help_text='Selecione o tipo mais adequado de despesa.', max_length=2, null=True, verbose_name='Tipo de despesa'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='arquivos',
            field=models.FileField(blank=True, null=True, upload_to='fundos/orcamentos', verbose_name='Arquivo de orçamento'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='arquivos',
            field=models.FileField(blank=True, null=True, upload_to='fundos/requisicoes', verbose_name='Arquivo de requisição de fundos'),
        ),
    ]
