# Generated by Django 4.2.4 on 2023-08-26 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
        ('locais', '0003_rename_proprietario_pj_da_ur_unidade_de_referencia_proprietario_pj_de_ur'),
        ('categorias', '0002_unidade_de_medida'),
        ('pessoas', '0002_rename_user_pessoa_usuario_pessoa_profissao'),
        ('fundos', '0004_alter_item_de_orcamento_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Insira o nome to serviço, material ou maquinário (item de orçamento)', max_length=120, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('MO', 'Mão de obra ou serviço'), ('MT', 'Materiais ou insumo'), ('MQ', 'Máquina ou equipamento')], help_text='Selecione o tipo mais adequado de item de orçamento.', max_length=2, null=True, verbose_name='Tipo de item')),
                ('quantidade', models.PositiveIntegerField(help_text='Especifique a quantidade que deseja adquirir considerando a unidade de medida especificada.', verbose_name='Qtd.')),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Especifique o preço unitário do item de orçamento.', max_digits=10, verbose_name='Preço unitário')),
                ('total_do_item', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total do item')),
                ('unidade', models.ForeignKey(blank=True, help_text='Selecione a unidade de medida do ítem de orçamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.unidade_de_medida', verbose_name='Un.')),
            ],
            options={
                'verbose_name': 'Item de orçamento',
                'verbose_name_plural': 'Itens de orçamento',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, help_text='Seleciona a data do orçamento fornecido.', null=True)),
                ('exclui', models.TextField(blank=True, help_text='Descreva o que o orçameto não inclui, quando pertinente.', null=True, verbose_name='Não incluso')),
                ('validade', models.PositiveIntegerField(blank=True, help_text='Especifique por quantos dias orçamento é válido.', null=True)),
                ('forma_de_garantia', models.CharField(blank=True, help_text='Explicite a forma e tempo de garantia do fornecedor.', max_length=200, null=True)),
                ('total_do_orcamento', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('dados_para_pagamento', models.TextField(blank=True, help_text='Inclua os dados para pagamento deste orçamento conforme preferência do fornecedor.', null=True, verbose_name='Dados para pagamento')),
                ('observacoes', models.TextField(blank=True, help_text='Insira quaisquer observações que considerar pertinente sobre esse orçamento.', null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='fundos/orcamentos')),
                ('empresa_fornecedora', models.ForeignKey(blank=True, help_text='Seleciona a instituição fornecedora do orçamento. Se não houver, clique em "+" para inserir.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.instituicao', verbose_name='Empresa fornecedora')),
                ('inclui', models.ManyToManyField(blank=True, help_text='Selecione os itens inclusos neste orçamento', to='fundos.item')),
                ('profissional_fornecedor', models.ForeignKey(blank=True, help_text='Selecione o profissional fornecedor. Senão houver, clieque em "+" para inserir.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='orcamento_para_solicitacao_de_fundos',
            name='empresa_fornecedora',
        ),
        migrations.RemoveField(
            model_name='orcamento_para_solicitacao_de_fundos',
            name='profissional_fornecedor',
        ),
        migrations.RemoveField(
            model_name='orcamento_para_solicitacao_de_fundos',
            name='solicitacao_de_fundos',
        ),
        migrations.RemoveField(
            model_name='solicitacao_de_fundos',
            name='data_da_solicitacao',
        ),
        migrations.RemoveField(
            model_name='solicitacao_de_fundos',
            name='municipio_solicitante',
        ),
        migrations.AddField(
            model_name='solicitacao_de_fundos',
            name='data',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Data da solicitação'),
        ),
        migrations.AddField(
            model_name='solicitacao_de_fundos',
            name='municipio',
            field=models.ForeignKey(blank=True, help_text='Selecione o município para onde irão os fundos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.municipio', verbose_name='Município solicitante'),
        ),
        migrations.AddField(
            model_name='solicitacao_de_fundos',
            name='total_da_solicitacao',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Item_de_orcamento',
        ),
        migrations.DeleteModel(
            name='orcamento_para_solicitacao_de_fundos',
        ),
        migrations.AddField(
            model_name='solicitacao_de_fundos',
            name='orcamentos',
            field=models.ManyToManyField(blank=True, help_text='Selecione três orçamentos para cada tipo de orçamento levantado.', to='fundos.orcamento'),
        ),
    ]
