# Generated by Django 4.2.4 on 2023-09-03 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundos', '0005_alter_compra_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='itens',
        ),
        migrations.AddField(
            model_name='item',
            name='orcamento',
            field=models.ForeignKey(blank=True, help_text='Selecione o orçamento a que esta compra de itens de despesa faz parte.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fundos.orcamento', verbose_name='Orçamento a que esta compra pertence'),
        ),
        migrations.AddField(
            model_name='item',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Especifique o preço unitário do item de orçamento.', max_digits=10, verbose_name='Preço unitário'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Especifique a quantidade que deseja adquirir considerando a unidade de medida do item de despesa.', max_digits=6, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='item',
            name='subtotal_do_item',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal do item de despesa'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criou_orcamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificou_orcamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(blank=True, help_text='Inclua uma breve descrição do item de despesa quando houver especificações técnicas.', max_length=80, null=True, verbose_name='Descrição'),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
