# Generated by Django 4.2.4 on 2023-08-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_fundo'),
        ('locais', '0003_rename_proprietario_pj_da_ur_unidade_de_referencia_proprietario_pj_de_ur'),
        ('projetos', '0002_rename_descrição_do_objetivo_especifico_objetivo_especifico_de_projeto_descricao_do_objetivo_especif'),
        ('instituicoes', '0001_initial'),
        ('fundos', '0005_item_orcamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao_de_fundos',
            options={'ordering': ('id',), 'verbose_name': 'Solicitação de orçamento', 'verbose_name_plural': 'Solicitações de orçamento'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_do_item',
        ),
        migrations.RemoveField(
            model_name='solicitacao_de_fundos',
            name='total_da_solicitacao',
        ),
        migrations.AddField(
            model_name='solicitacao_de_fundos',
            name='fundo_solicitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.fundo', verbose_name='Fundo de financiamento'),
        ),
        migrations.AddField(
            model_name='solicitacao_de_fundos',
            name='instituicao_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicoes.instituicao', verbose_name='Insituição solicitante'),
        ),
        migrations.RemoveField(
            model_name='solicitacao_de_fundos',
            name='atividade_vinculada',
        ),
        migrations.RemoveField(
            model_name='solicitacao_de_fundos',
            name='etapa_vinculada',
        ),
        migrations.RemoveField(
            model_name='solicitacao_de_fundos',
            name='objetivo_especifico_vinculado',
        ),
        migrations.AlterField(
            model_name='solicitacao_de_fundos',
            name='orcamentos',
            field=models.ManyToManyField(blank=True, help_text='Selecione três orçamentos.', to='fundos.orcamento'),
        ),
        migrations.RemoveField(
            model_name='solicitacao_de_fundos',
            name='ur_vinculada',
        ),
        migrations.CreateModel(
            name='Pedido_de_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(help_text='Especifique a quantidade que deseja adquirir considerando a unidade de medida do item.', verbose_name='Qtd.')),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Especifique o preço unitário do item de orçamento.', max_digits=10, verbose_name='Preço unitário')),
                ('total_do_item', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total do item')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fundos.item', verbose_name='Pedido de item')),
            ],
            options={
                'verbose_name': 'Pedido de item',
                'verbose_name_plural': 'Pedidos de itens',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='inclui',
            field=models.ManyToManyField(blank=True, help_text='Selecione o(s) pedido(s) de itens deste orçamento', to='fundos.pedido_de_item'),
        ),
        migrations.AddField(
            model_name='solicitacao_de_fundos',
            name='atividade_vinculada',
            field=models.ManyToManyField(blank=True, help_text='Selecione a(s) atividade(s) a que esta solicitação está diretamente vinculada.', to='projetos.atividade'),
        ),
        migrations.AddField(
            model_name='solicitacao_de_fundos',
            name='etapa_vinculada',
            field=models.ManyToManyField(blank=True, help_text='Selecione a(s) etapa(s) a que esta solicitação está diretamente vinculada, se houver', to='projetos.etapa', verbose_name='Etapa(s) vinculada(s)'),
        ),
        migrations.AddField(
            model_name='solicitacao_de_fundos',
            name='objetivo_especifico_vinculado',
            field=models.ManyToManyField(blank=True, help_text='Selecione o objetivo específico a que esta solicitação está diretamente vincula.', to='projetos.objetivo_especifico_de_projeto', verbose_name='Objetivo(s) específico(s) vinculado(s) à solicitação de fundos'),
        ),
        migrations.AddField(
            model_name='solicitacao_de_fundos',
            name='ur_vinculada',
            field=models.ManyToManyField(blank=True, help_text='Selecione uma ou mais URs destino dos fundos dessa solicitação, se houver.', to='locais.unidade_de_referencia', verbose_name='UR(s) vinculada(s) à solicitação de fundos'),
        ),
    ]
