# Generated by Django 4.2.4 on 2023-08-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0006_alter_solicitacao_de_fundos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao_de_fundos',
            options={'ordering': ('id',), 'verbose_name': 'Solicitação de fundo', 'verbose_name_plural': 'Solicitações de fundos'},
        ),
        migrations.AlterField(
            model_name='solicitacao_de_fundos',
            name='orcamentos',
            field=models.ManyToManyField(blank=True, help_text='Selecione três orçamentos.', to='fundos.orcamento', verbose_name='Orçamentos'),
        ),
    ]
