# Generated by Django 4.2.4 on 2023-08-31 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0008_solicitacao_de_fundos_arquivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',), 'verbose_name': 'Item de compra', 'verbose_name_plural': 'Itens de compra'},
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='inclui',
        ),
        migrations.RemoveField(
            model_name='pedido_de_item',
            name='total_do_item',
        ),
        migrations.RemoveField(
            model_name='solicitacao_de_fundos',
            name='orcamentos',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_NF',
            field=models.DateField(blank=True, help_text='Insira da data de emissão da NF.', null=True, verbose_name='Data da NF'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_RPA',
            field=models.DateField(blank=True, help_text='Insira da data de emissão do RPA.', null=True, verbose_name='Data da NF'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='numero_NF',
            field=models.CharField(blank=True, help_text='Insira o número da NF após compra confirmada', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='numero_RPA',
            field=models.CharField(blank=True, help_text='Insira o número do RPS após a compra confirmada', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='solicitacao',
            field=models.ForeignKey(blank=True, help_text='Selecione a solicitação de fundos em que este orçamento se insere.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundos.solicitacao_de_fundos', verbose_name='Solicitação de fundos'),
        ),
        migrations.AddField(
            model_name='pedido_de_item',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundos.orcamento'),
        ),
        migrations.AddField(
            model_name='pedido_de_item',
            name='total_do_pedido_do_item',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal do item'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='exclui',
            field=models.TextField(blank=True, help_text='Especifique o que não está incluso neste orçamento, quando pertinente.', null=True, verbose_name='Não incluso neste orçamento'),
        ),
        migrations.AlterField(
            model_name='pedido_de_item',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fundos.item', verbose_name='Item solicitado'),
        ),
        migrations.AlterField(
            model_name='pedido_de_item',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, help_text='Especifique a quantidade que deseja adquirir considerando a unidade de medida do item.', max_digits=6, verbose_name='Qtd.'),
        ),
        migrations.AlterField(
            model_name='solicitacao_de_fundos',
            name='data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data da solicitação'),
        ),
    ]
