# Generated by Django 4.2.4 on 2023-09-04 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundos', '0008_requisicao_atualizado_em_requisicao_atualizado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
