# Generated by Django 4.2.4 on 2023-08-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0009_alter_item_options_remove_orcamento_inclui_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, help_text='Inclua uma breve descrição do item quando houver especificações técnicas.', null=True, verbose_name='Descrição'),
        ),
    ]
