# Generated by Django 4.2.4 on 2023-09-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_fundo'),
        ('fundos', '0010_item_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_de_item',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade de medida do item.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.unidade_de_medida'),
        ),
    ]
