# Generated by Django 4.2.4 on 2023-09-06 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0012_categoria_de_despesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundos', '0011_item_atualizado_em_item_atualizado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='orcamento',
        ),
        migrations.RemoveField(
            model_name='item',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subtotal_do_item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unidade',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, help_text='Inclua uma breve descrição do item de despesa quando houver especificações técnicas.', max_length=80, null=True, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, help_text='Especifique a quantidade que deseja adquirir.', max_digits=6, verbose_name='QTD')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Especifique o preço unitário do item.', max_digits=10, verbose_name='Preço Un.')),
                ('subtotal_do_item', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('id_codificada', models.CharField(blank=True, editable=False, max_length=60, null=True, unique=True, verbose_name='ID Codificada')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_criados', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='Selecione um item para este pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='fundos.item')),
                ('orcamento', models.ForeignKey(blank=True, help_text='Selecione em que orçamento esse pedido se insere.', null=True, on_delete=django.db.models.deletion.CASCADE, to='fundos.orcamento')),
                ('tipo', models.ForeignKey(blank=True, help_text='Selecione a categoria de despesa.', null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria_de_despesa', verbose_name='Tipo de despesa')),
                ('unidade', models.ForeignKey(blank=True, help_text='Selecione a unidade de medida do ítem de despesa no orçamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.unidade_de_medida', verbose_name='Un')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('id',),
            },
        ),
    ]
