# Generated by Django 4.2.4 on 2023-09-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_fundo'),
        ('fundos', '0011_pedido_de_item_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',), 'verbose_name': 'Item de despesa', 'verbose_name_plural': 'Itens de despesa'},
        ),
        migrations.AlterModelOptions(
            name='pedido_de_item',
            options={'ordering': ('id',), 'verbose_name': 'Ítem de despesa', 'verbose_name_plural': 'Ítens de despesa'},
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, help_text='Inclua uma breve descrição do item de despesa no orçamento quando houver especificações técnicas.', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(blank=True, help_text='Insira o nome ou título do serviço, material ou maquinário (item de despesa no orçamento)', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(blank=True, choices=[('MO', 'Mão de obra ou serviço'), ('MT', 'Materiais ou insumo'), ('MQ', 'Máquina ou equipamento')], help_text='Selecione o tipo mais adequado de despesa.', max_length=2, null=True, verbose_name='Tipo de despesa'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade de medida do ítem de despesa no orçamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.unidade_de_medida', verbose_name='Un.'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='dados_para_pagamento',
            field=models.TextField(blank=True, help_text='Inclua os dados para pagamento deste orçamento conforme preferência do fornecedor (Pix, dados para depósito, etc.).', null=True, verbose_name='Dados para pagamento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='exclui',
            field=models.TextField(blank=True, help_text='Especifique o que não está incluso neste orçamento, caso seja relevante esclarecer.', null=True, verbose_name='O que não está incluso neste orçamento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='forma_de_garantia',
            field=models.CharField(blank=True, help_text='Explicite a forma e tempo de garantia do fornecedor.', max_length=200, null=True, verbose_name='Forma e tempo de garantia do fornecedor'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Insira quaisquer observações adicionais que considerar pertinente sobre esse orçamento.', null=True, verbose_name='Observações adicionais'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='solicitacao',
            field=models.ForeignKey(blank=True, help_text='Selecione a Solicitação de Fundos em que este Orçamento e faz parte.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundos.solicitacao_de_fundos', verbose_name='Solicitação de Fundos'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='total_do_orcamento',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor total do orçamento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Especifique por quantos dias este orçamento é válido.', null=True, verbose_name='Validade do orçamento'),
        ),
        migrations.AlterField(
            model_name='pedido_de_item',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Selecione o item de despesa para esse pedido.', null=True, on_delete=django.db.models.deletion.CASCADE, to='fundos.item', verbose_name='Item de despesa'),
        ),
        migrations.AlterField(
            model_name='pedido_de_item',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundos.orcamento', verbose_name='Selecione o orçamento a que este item de despesa faz parte.'),
        ),
        migrations.AlterField(
            model_name='pedido_de_item',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, help_text='Especifique a quantidade que deseja adquirir considerando a unidade de medida do item de despesa.', max_digits=6, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido_de_item',
            name='total_do_pedido_do_item',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal do item de despesa'),
        ),
        migrations.AlterField(
            model_name='pedido_de_item',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade de medida do item de despesa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.unidade_de_medida'),
        ),
    ]
