# Generated by Django 4.2.4 on 2023-09-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0012_remove_item_descricao_remove_item_orcamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ('id',), 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
    ]
