# Generated by Django 4.2.4 on 2023-09-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0012_categoria_de_despesa'),
        ('fundos', '0013_alter_orcamento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='unidade',
        ),
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.CharField(blank=True, help_text='Inclua uma breve descrição do item de despesa quando houver especificações técnicas.', max_length=80, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='item',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade de medida do ítem de despesa no orçamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.unidade_de_medida', verbose_name='Un'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='especificacao',
            field=models.CharField(blank=True, help_text='Inclua especificações do item de despesa quando houver especificações técnicas.', max_length=80, null=True, verbose_name='Especificação'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(blank=True, help_text='Insira o nome produto ou serviço.', max_length=60, null=True),
        ),
    ]
