# Generated by Django 4.2.4 on 2023-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0014_remove_pedido_descricao_remove_pedido_unidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id_codificada',
            field=models.CharField(blank=True, editable=False, max_length=90, null=True, unique=True, verbose_name='ID Codificada'),
        ),
    ]
