# Generated by Django 4.2.4 on 2023-09-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0016_alter_item_descricao_alter_item_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='objetivo_especifico_vinculado',
        ),
    ]
