# Generated by Django 4.2.4 on 2023-09-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='responsavel_pela_instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa', verbose_name='Pessoa responsável, representante ou âncora da instituição'),
        ),
    ]
