# Generated by Django 4.2.4 on 2023-09-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('instituicoes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='responsavel_pela_instituicao',
            field=models.ForeignKey(blank=True, help_text='Selecione o nome da pessoa responsável, representante ou âncora da instituição', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa', verbose_name='Contato'),
        ),
    ]
