# Generated by Django 4.2.4 on 2023-09-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0003_remove_unidade_de_referencia_latitude_da_ur_and_more'),
        ('instituicoes', '0003_alter_instituicao_responsavel_pela_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.municipio', verbose_name='Município sede da instituição'),
        ),
    ]
